version: '3.7'

services:
    postfix:
        image: cosmicexplorer/mailman-postfix:2
        volumes:
            - ${STORAGE_PATH}:/opt/mailman
        environment:
            - POSTFIX_RELAYHOST=${POSTFIX_RELAYHOST}
            - POSTFIX_MYHOSTNAME=${POSTFIX_MAILNAME}
            - POSTFIX_MYNETWORKS=${POSTFIX_MYNETWORKS}
        ports:
            - "128.230.21.179:25:25"
        networks:
            mailman-bridge:
                ipv4_address: 192.168.102.3
            roster-net: {}
        restart: always

networks:
    roster-net:
        external: true
        name: roster_roster-net
    mailman-bridge:
        external: true
        name: mail_mailman-bridge
